[
    {
        "_id": "652792b28a1e34283bfff21c",
        "timerecordId": "NaN",
        "workplaceId": "399-689",
        "workplaceName": "เพ็ท โฟกัส",
        "date": "21/07/2023",
        "employeeRecord": [
            {
                "staffId": "660307",
                "staffName": "กรวิชญ์",
                "shift": "morning_shift",
                "startTime": "07.50",
                "endTime": "17.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652792b28a1e34283bfff21d"
            },
            {
                "staffId": "660306",
                "staffName": "สมคิด ",
                "shift": "morning_shift",
                "startTime": "06.45",
                "endTime": "16.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652792b28a1e34283bfff21e"
            },
            {
                "staffId": "651194",
                "staffName": "พีรพงษ์",
                "shift": "afternoon_shift",
                "startTime": "14.00",
                "endTime": "00.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652792b28a1e34283bfff21f"
            },
            {
                "staffId": "651300",
                "staffName": "ชูชาติ",
                "shift": "night_shift",
                "startTime": "22.46",
                "endTime": "08.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652792b28a1e34283bfff220"
            },
            {
                "staffId": "650073",
                "staffName": "ศรราม ",
                "shift": "night_shift",
                "startTime": "22.50",
                "endTime": "08.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652792b28a1e34283bfff221"
            },
            {
                "staffId": "",
                "staffName": "",
                "shift": "",
                "startTime": "",
                "endTime": "",
                "allTime": "",
                "otTime": "",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652792b28a1e34283bfff222"
            },
            {
                "staffId": "",
                "staffName": "",
                "shift": "",
                "startTime": "08.00",
                "endTime": "17.00",
                "allTime": "",
                "otTime": "",
                "selectotTime": "17.00",
                "selectotTimeOut": "",
                "_id": "652792b28a1e34283bfff223"
            }
        ],
        "__v": 0
    },
    {
        "_id": "652792b48a1e34283bfff239",
        "timerecordId": "NaN",
        "workplaceId": "399-689",
        "workplaceName": "เพ็ท โฟกัส",
        "date": "21/07/2023",
        "employeeRecord": [
            {
                "staffId": "",
                "staffName": "",
                "shift": "",
                "startTime": "",
                "endTime": "",
                "allTime": "",
                "otTime": "",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652792b48a1e34283bfff23a"
            },
            {
                "staffId": "660307",
                "staffName": "กรวิชญ์",
                "shift": "morning_shift",
                "startTime": "07.50",
                "endTime": "17.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652792b48a1e34283bfff23b"
            },
            {
                "staffId": "660306",
                "staffName": "สมคิด ",
                "shift": "morning_shift",
                "startTime": "06.45",
                "endTime": "16.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652792b48a1e34283bfff23c"
            },
            {
                "staffId": "651194",
                "staffName": "พีรพงษ์",
                "shift": "afternoon_shift",
                "startTime": "14.00",
                "endTime": "00.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652792b48a1e34283bfff23d"
            },
            {
                "staffId": "651300",
                "staffName": "ชูชาติ",
                "shift": "night_shift",
                "startTime": "22.46",
                "endTime": "08.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652792b48a1e34283bfff23e"
            },
            {
                "staffId": "650073",
                "staffName": "ศรราม ",
                "shift": "night_shift",
                "startTime": "22.50",
                "endTime": "08.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652792b48a1e34283bfff23f"
            },
            {
                "staffId": "",
                "staffName": "",
                "shift": "",
                "startTime": "",
                "endTime": "",
                "allTime": "",
                "otTime": "",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652792b48a1e34283bfff240"
            },
            {
                "staffId": "",
                "staffName": "",
                "shift": "",
                "startTime": "08.00",
                "endTime": "17.00",
                "allTime": "",
                "otTime": "",
                "selectotTime": "17.00",
                "selectotTimeOut": "",
                "_id": "652792b48a1e34283bfff241"
            }
        ],
        "__v": 0
    },
    {
        "_id": "652794b08a1e34283bfff2e8",
        "timerecordId": "NaN",
        "workplaceId": "399-689",
        "workplaceName": "เพ็ท โฟกัส",
        "date": "22/07/2023",
        "employeeRecord": [
            {
                "staffId": "660307",
                "staffName": "กรวิชญ์",
                "shift": "morning_shift",
                "startTime": "06.00",
                "endTime": "16.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652794b08a1e34283bfff2e9"
            },
            {
                "staffId": "660306",
                "staffName": "สมคิด ",
                "shift": "morning_shift",
                "startTime": "06.50",
                "endTime": "16.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652794b08a1e34283bfff2ea"
            },
            {
                "staffId": "651194",
                "staffName": "พีรพงษ์",
                "shift": "afternoon_shift",
                "startTime": "15.00",
                "endTime": "00.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652794b08a1e34283bfff2eb"
            },
            {
                "staffId": "651300",
                "staffName": "ชูชาติ",
                "shift": "night_shift",
                "startTime": "22.028",
                "endTime": "08.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652794b08a1e34283bfff2ec"
            },
            {
                "staffId": "660305",
                "staffName": "ขวัญชัย",
                "shift": "night_shift",
                "startTime": "22.28",
                "endTime": "08.02",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652794b08a1e34283bfff2ed"
            },
            {
                "staffId": "",
                "staffName": "",
                "shift": "",
                "startTime": "",
                "endTime": "",
                "allTime": "",
                "otTime": "",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652794b08a1e34283bfff2ee"
            },
            {
                "staffId": "",
                "staffName": "",
                "shift": "",
                "startTime": "",
                "endTime": "",
                "allTime": "",
                "otTime": "",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "652794b08a1e34283bfff2ef"
            }
        ],
        "__v": 0
    },
    {
        "_id": "6527a2ac8a1e34283bfff572",
        "timerecordId": "NaN",
        "workplaceId": "399-689",
        "workplaceName": "เพ็ท โฟกัส",
        "date": "23/07/2023",
        "employeeRecord": [
            {
                "staffId": "660307",
                "staffName": "กรวิชญ์",
                "shift": "morning_shift",
                "startTime": "06.58",
                "endTime": "16.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527a2ac8a1e34283bfff573"
            },
            {
                "staffId": "660306",
                "staffName": "สมคิด ",
                "shift": "morning_shift",
                "startTime": "06.00",
                "endTime": "16.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527a2ac8a1e34283bfff574"
            },
            {
                "staffId": "651194",
                "staffName": "พีรพงษ์",
                "shift": "afternoon_shift",
                "startTime": "14.18",
                "endTime": "00.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527a2ac8a1e34283bfff575"
            },
            {
                "staffId": "650073",
                "staffName": "ศรราม ",
                "shift": "night_shift",
                "startTime": "22.50",
                "endTime": "08.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527a2ac8a1e34283bfff576"
            },
            {
                "staffId": "660305",
                "staffName": "ขวัญชัย",
                "shift": "night_shift",
                "startTime": "22.32",
                "endTime": "08.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527a2ac8a1e34283bfff577"
            },
            {
                "staffId": "",
                "staffName": "",
                "shift": "",
                "startTime": "",
                "endTime": "",
                "allTime": "",
                "otTime": "",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527a2ac8a1e34283bfff578"
            },
            {
                "staffId": "",
                "staffName": "",
                "shift": "",
                "startTime": "",
                "endTime": "",
                "allTime": "",
                "otTime": "",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527a2ac8a1e34283bfff579"
            }
        ],
        "__v": 0
    },
    {
        "_id": "6527a37f8a1e34283bfff5b9",
        "timerecordId": "NaN",
        "workplaceId": "399-689",
        "workplaceName": "เพ็ท โฟกัส",
        "date": "15/08/2023",
        "employeeRecord": [
            {
                "staffId": "660307",
                "staffName": "กรวิชญ์",
                "shift": "afternoon_shift",
                "startTime": "12.39",
                "endTime": "22.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527a37f8a1e34283bfff5ba"
            },
            {
                "staffId": "651194",
                "staffName": "พีรพงษ์",
                "shift": "afternoon_shift",
                "startTime": "12.50",
                "endTime": "22.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527a37f8a1e34283bfff5bb"
            },
            {
                "staffId": "651300",
                "staffName": "ชูชาติ",
                "shift": "night_shift",
                "startTime": "22.00",
                "endTime": "08.03",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527a37f8a1e34283bfff5bc"
            },
            {
                "staffId": "650073",
                "staffName": "ศรราม ",
                "shift": "afternoon_shift",
                "startTime": "12.00",
                "endTime": "22.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527a37f8a1e34283bfff5bd"
            },
            {
                "staffId": "660305",
                "staffName": "ขวัญชัย",
                "shift": "afternoon_shift",
                "startTime": "12.00",
                "endTime": "22.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527a37f8a1e34283bfff5be"
            },
            {
                "staffId": "",
                "staffName": "",
                "shift": "",
                "startTime": "",
                "endTime": "",
                "allTime": "",
                "otTime": "",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527a37f8a1e34283bfff5bf"
            },
            {
                "staffId": "",
                "staffName": "",
                "shift": "",
                "startTime": "",
                "endTime": "",
                "allTime": "",
                "otTime": "",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527a37f8a1e34283bfff5c0"
            }
        ],
        "__v": 0
    },
    {
        "_id": "6527ab0e8a1e34283bfff871",
        "timerecordId": "NaN",
        "workplaceId": "399-689",
        "workplaceName": "เพ็ท โฟกัส",
        "date": "16/08/2023",
        "employeeRecord": [
            {
                "staffId": "660826",
                "staffName": "พยง ",
                "shift": "morning_shift",
                "startTime": "07.045",
                "endTime": "17.05",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527ab0e8a1e34283bfff872"
            },
            {
                "staffId": "660307",
                "staffName": "กรวิชญ์",
                "shift": "morning_shift",
                "startTime": "06.49",
                "endTime": "16.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527ab0e8a1e34283bfff873"
            },
            {
                "staffId": "651194",
                "staffName": "พีรพงษ์",
                "shift": "afternoon_shift",
                "startTime": "14.45",
                "endTime": "00.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527ab0e8a1e34283bfff874"
            },
            {
                "staffId": "651300",
                "staffName": "ชูชาติ",
                "shift": "night_shift",
                "startTime": "22.51",
                "endTime": "08.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527ab0e8a1e34283bfff875"
            },
            {
                "staffId": "650073",
                "staffName": "ศรราม ",
                "shift": "morning_shift",
                "startTime": "06.50",
                "endTime": "16.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527ab0e8a1e34283bfff876"
            },
            {
                "staffId": "660305",
                "staffName": "ขวัญชัย",
                "shift": "night_shift",
                "startTime": "22.00",
                "endTime": "08.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527ab0e8a1e34283bfff877"
            },
            {
                "staffId": "",
                "staffName": "",
                "shift": "",
                "startTime": "08.00",
                "endTime": "17.00",
                "allTime": "",
                "otTime": "",
                "selectotTime": "17.00",
                "selectotTimeOut": "",
                "_id": "6527ab0e8a1e34283bfff878"
            }
        ],
        "__v": 0
    },
    {
        "_id": "6527b5bc2aed89ff32b88be9",
        "timerecordId": "NaN",
        "workplaceId": "399-689",
        "workplaceName": "เพ็ท โฟกัส",
        "date": "24/07/2023",
        "employeeRecord": [
            {
                "staffId": "660307",
                "staffName": "กรวิชญ์",
                "shift": "morning_shift",
                "startTime": "07.49",
                "endTime": "17.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527b5bc2aed89ff32b88bea"
            },
            {
                "staffId": "660306",
                "staffName": "สมคิด ",
                "shift": "morning_shift",
                "startTime": "06.51",
                "endTime": "16.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527b5bc2aed89ff32b88beb"
            },
            {
                "staffId": "651194",
                "staffName": "พีรพงษ์",
                "shift": "afternoon_shift",
                "startTime": "14.44",
                "endTime": "00.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527b5bc2aed89ff32b88bec"
            },
            {
                "staffId": "651300",
                "staffName": "ชูชาติ",
                "shift": "morning_shift",
                "startTime": "06.48",
                "endTime": "16.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527b5bc2aed89ff32b88bed"
            },
            {
                "staffId": "650073",
                "staffName": "ศรราม ",
                "shift": "night_shift",
                "startTime": "22.51",
                "endTime": "08.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527b5bc2aed89ff32b88bee"
            },
            {
                "staffId": "660305",
                "staffName": "ขวัญชัย",
                "shift": "night_shift",
                "startTime": "22.29",
                "endTime": "08.00",
                "allTime": "8.0",
                "otTime": "0.0",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527b5bc2aed89ff32b88bef"
            },
            {
                "staffId": "",
                "staffName": "",
                "shift": "",
                "startTime": "",
                "endTime": "",
                "allTime": "",
                "otTime": "",
                "selectotTime": "",
                "selectotTimeOut": "",
                "_id": "6527b5bc2aed89ff32b88bf0"
            }
        ],
        "__v": 0
    }
]